Organism:
  # Number if organisms
  - 1
converttofast:
  - 'Trinit2y.fasta  Trinity.fasta  ZHour.fastq'

Sample:
  # One organism = one line
  # for each organism write every file like so:
  - 'Trinit2y  Trinity  ZHour'
