    ################################################################################
		#                                                                              #
		# Copyright 2017 Megaprobe-Lab                                                 #
		#                                                                              #
		# This is software created by the megaprobe lab under the GPL3 license.        #
		#                                                                              #
		# This program reproduces the pipeline for de novo rna sequencing research. To #
		# run the program, just move into the folder that contains the Snakefile and   #
		# make sure the PATH has addeded Trinity, khmer, screed and                    #
		# sourmash. For more explanation on what the program does read technical       #
		# report or to see usage read the README.md                                    #
		#                                                                              #
		# Then utilize the command: "snakemake" to run the desired operation.          #
		################################################################################


# Be sure to have all the / including the last one


# One organism = one line
# for each organism write every file like so:
# OrganismPATH:
# - "/home/kevin/first-test/Organism1"

OrganismPATH: #requiered 
  - "/data/kevin/workarea/pepino/"
  - "/data/kevin/workarea/labrat/"
 
Workdir: #requiered 
  - "/data/kevin/workarea/"

TrimmomaticPath: #requiered 
  - "/home/kevin/ThisSemester/Programs/Trimmomatic-0.36/"

ComparisonList: #requiered if more than one organism
  - "0 1"

MaxMemory: #requiered, you shouldn't use all your memory...
  - ""


